### ISSUE TITLE
Framerate dropping

### ISSUE THREAD

**Issue by Timothyoung97** [Team-Aston-Martin-Henz/Cyberacer#13]
Framerate has dropped significantly but inconsistently over the past few days through development. 
@david-eom try to see if it is the same on your end, maybe is just due to my laptop's CPU

**Comment by david-eom** [comment]
Tried on my side, frame rate doesn't seem to drop, maybe it is due to the heavy rendering of the entire scene on top.
However, I found out a few more things to be improved, will open issues accordingly.
