### ISSUE TITLE
Cars stuck forever

### ISSUE THREAD

**Issue by Timothyoung97** [Team-Aston-Martin-Henz/Cyberacer#17]
![image](https://user-images.githubusercontent.com/62177572/121389976-81c2f800-c97f-11eb-9e30-acc8003067c3.png)

I think there are some if-else conditions being overlooked, probably in the skipping checkpoint segment in CarController

**Comment by Timothyoung97** [comment]
![image](https://user-images.githubusercontent.com/62177572/121392853-57bf0500-c982-11eb-8fb9-63b1f821b5ae.png)

Tested for 10 times -> I think there is some alignment issue after refactoring

**Comment by david-eom** [comment]
Alright am on it, my guess would be the bug is somewhere in `UpdateAISpeedAndTurn()`, the AI cars are registering checkpoints correctly, but when they are moving from checkpoint to checkpoint they are having some hiccups.

**Comment by Timothyoung97** [comment]
Solved by @david-eom 
Checked and Closed.
