### ISSUE TITLE
Checkpoints in Cyber City track not set at start/finish line

### ISSUE THREAD

**Issue by david-eom** [Team-Aston-Martin-Henz/Cyberacer#33]
With reference to #24, the checkpoint checker will increment one lap if the player car reaches the ramp instead of the start/finish line. It can also be viewed in the screenshot under #24.
This is a bug of low priority and should be easily fixed by rearranging/reshaping the checkpoints in the map.

**Comment by Timothyoung97** [comment]
Track 2 Start/Finish Line Bug Fixed:
- Solution: By setting the start/finish checkpoint to the end of the array in RaceManager. This allows the start/finish line checkpoint to be the last checkpoint that will increment the lap count. As such, allowing the race to end at the finish line.

![tempsnip](https://user-images.githubusercontent.com/62177572/124493873-b2644900-dde8-11eb-9b7c-5e4fa80fedef.png)
