### ISSUE TITLE
Desert Track: Lagging due to too many objects 

### ISSUE THREAD

**Issue by Timothyoung97** [Team-Aston-Martin-Henz/Cyberacer#34]
First Attempt: Making items that are not moving as static GameObejcts.
Feedback: Frame rate increases from averaging 7 fps to ~11 fps.

**Comment by Timothyoung97** [comment]
Second Attempt: Removed from houses hidden beneath the ground.
Feedback: Frame rate increases from averaging 11 fps to ~20 fps in the non-populated regions. In populated regions, frame rate will take a sharp dip to around 11 fps.

**Comment by david-eom** [comment]
Lagging visibly alleviated with #35.

**Comment by david-eom** [comment]
Fixed by #49.
