### ISSUE TITLE
`NullReferenceException` being thrown from calling `CarController::CheckpointHit`

### ISSUE THREAD

**Issue by david-eom** [Team-Aston-Martin-Henz/Cyberacer#4]
When `CheckpointChecker` detects collision with trigger-type box collider, correct `cpNumber` is identified, yet null reference exception is thrown when calling  `CheckpointHit`.

**Error message:**
```
NullReferenceException: Object reference not set to an instance of an object CheckpointChecker.OnTriggerEnter (UnityEngine.Collider other) (at Assets/Scripts/CheckpointChecker.cs:16)
```

**Comment by Timothyoung97** [comment]
Maybe due to the Checkpoint, the "Is Trigger" checkbox needed to be ticked on inspector

**Comment by david-eom** [comment]
Solved the issue, `isTrigger` is already ticked, but turns out I forgot to assign the car to`CheckpointChecker` script under `Sphere`.
Suggestion: maybe inside the script we should use certain kind of label to mark out the public variables that haven't been instantiated yet.
