### ISSUE TITLE
Player car is not a Prefab

### ISSUE THREAD

**Issue by david-eom** [Team-Aston-Martin-Henz/Cyberacer#8]
For efficiency and uniformity, player car should be a Prefab Asset.
The player car is not a Prefab yet as of commit  f3e4490956950873ed4408e7a5971b8ff55df040.

**Comment by Timothyoung97** [comment]
For track 1, I unpack the prefab as there are some alignment issues between the sphere and the car body. When we complete track 1 as a whole, we can repack the player car as a prefab for future usage
